services:
  grantan:
    container_name: grantan
    build:
      context: .
    ports:
      - "6789:6789"
    environment:
      PORT: "6789"
      DATA_DIR: /data
      STATIC_DIR: /app/public
    volumes:
      - ./data:/data
    restart: unless-stopped
