services:
  grantan:
    container_name: grantan
    build:
      context: .
    ports:
      - "5678:5678"
    environment:
      PORT: "5678"
      DATA_DIR: /data
      STATIC_DIR: /app/public
    volumes:
      - ./data:/data
    restart: unless-stopped
